development:
  endpoint: "http://www.google-analytics.com/collect"
  version: 1
  tracking_code: UA-77165304-1

production:
  endpoint: "http://www.google-analytics.com/collect"
  version: 1
  tracking_code: UA-77165304-1
